version: '3.8'
x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
  AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
  AIRFLOW__CORE__DAGS_FOLDER: ${AIRFLOW__CORE__DAGS_FOLDER}
  AIRFLOW__CORE__PLUGINS_FOLDER: ${AIRFLOW__CORE__PLUGINS_FOLDER}
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: ${AIRFLOW__LOGGING__BASE_LOG_FOLDER}
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  AIRFLOW__SMTP__SMTP_HOST:  ${AIRFLOW__SMTP__SMTP_HOST}
  AIRFLOW__SMTP__SMTP_STARTTLS: ${AIRFLOW__SMTP__SMTP_STARTTLS}
  AIRFLOW__SMTP__SMTP_SSL: ${AIRFLOW__SMTP__SMTP_SSL}
  AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
  AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
  AIRFLOW__SMTP__SMTP_PORT: ${AIRFLOW__SMTP__SMTP_PORT}
  AIRFLOW__SMTP__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP__SMTP_MAIL_FROM}
  AIRFLOW__SMTP__SMTP__SMTP_TIMEOUT: ${AIRFLOW__SMTP__SMTP__SMTP_TIMEOUT}
  AIRFLOW__SMTP__SMTP__SMTP_RETRY_LIMIT: ${AIRFLOW__SMTP__SMTP__SMTP_RETRY_LIMIT}


x-airflow-connection-env: &airflow-conn-env
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
  AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW_CELERY_RESULT_BACKEND}
  AIRFLOW__CELERY__BROKEN_URL: ${CELERY_BROKER_URL}

x-airflow-core-mounts: &airflow-core-mounts
  - airflow_logs_volume:/project_files/src/logs
  - airflow_dags_volume:/project_files/src/dags
  - airflow_plugins_volume:/project_files/src/plugins

x-airflow-project-mounts: &airflow-project-mounts
  - /Users/alibashir/Desktop/workspace.nosync/ETL/weather_reports_etl/project_requirements.txt:/project_requirements.txt
  - /Users/alibashir/Desktop/workspace.nosync/ETL/weather_reports_etl/project_files/src:/project_files/src

x-airflow-comm: &airflow-common
  build: "Docker/airflow"
  restart: always


services:
  weather_db_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - wr_vl:/var/lib/postgresql/data
      - /Users/alibashir/Desktop/workspace.nosync/ETL/weather_reports_etl/Docker/weather_db/resources:/resources
      - /Users/alibashir/Desktop/workspace.nosync/ETL/weather_reports_etl/Docker/weather_db/scripts:/scripts
      - /Users/alibashir/Desktop/workspace.nosync/ETL/weather_reports_etl/Docker/weather_db/scripts/sql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "alibashir"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-msg-broker:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
    restart: always


  airflow-webserver:
    <<: *airflow-common
    environment:
      <<: [ *airflow-common-env, *airflow-conn-env ]
    volumes:
      *airflow-core-mounts
    ports:
      - 8080:8080
    depends_on:
      - weather_db_postgres
      - airflow-msg-broker
    command:
      - webserver
    healthcheck:
      test: [ "CMD","curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 30s
      retries: 3

  airflow-flower:
    <<: *airflow-common
    environment:
      << : *airflow-conn-env
    ports:
      - "5555:5555"
    depends_on:
      - airflow-msg-broker
      - weather_db_postgres
    command: flower
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5555/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  airflow-scheduler:
    << : *airflow-common
    environment:
      <<: [ *airflow-common-env, *airflow-conn-env ]
    volumes:
      *airflow-project-mounts
    command:
      - scheduler
    depends_on:
      - airflow-webserver
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  airflow-worker:
    << : *airflow-common
    environment:
      <<: [ *airflow-common-env, *airflow-conn-env ]
      REDIS_PASS: ${REDIS_PASSWORD}
    volumes:
      *airflow-project-mounts
    command: worker
    depends_on:
      - airflow-scheduler
      - airflow-msg-broker
      - weather_db_postgres
#    healthcheck:
#      test: ["CMD-SHELL", 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 30s

volumes:
  wr_vl:
    driver: local
  airflow_logs_volume:
      driver: local
  airflow_dags_volume:
      driver: local
  airflow_plugins_volume:
        driver: local
  airflow_config_volume:
        driver: local

