CREATE DATABASE airflow;
CREATE USER airflow_user WITH PASSWORD 'airflowuser123!' LOGIN;
GRANT CONNECT ON DATABASE airflow to airflow_user;
GRANT ALL PRIVILEGES ON DATABASE airflow to airflow_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO airflow_user;
ALTER DATABASE AIRFLOW OWNER  TO airflow_user;





